Ext.define('Admin.view.cekinfokendaraan.CekInfoKendaraanView', {
    extend: 'Ext.Panel',
    xtype: 'cekinfokendaraan-view',

    requires: [
        'Ext.dataview.DataView' 
    ],
    
    listeners: {
        added: 'onLoadView'
    },

    title: 'Detail Kendaraan',
    scrollable: true,
    items: [{
        xtype: 'dataview',    
        store: {
            type: 'cekinfokendaraan',
            autoLoad: false
        },
        
        cls: 'cek-info-kendaraan-view',
        itemTpl: 
            new Ext.XTemplate(
                '<div class="card">', 

                    '<div class="text-center">', 
                        '<div style="color: #808080; font-weight: bold; padding: 10px; margin: 0 0 10px 0; font-size: 28px;">{nopol_kode_kota} {nopol_kode_kendaraan} {nopol_kode_wilayah}</div>',        
                    '</div>', 

                    '<div style="background-color: #8C8C8C; color: white; padding: 10px; margin: 0 0 10px 0; font-size: 17px;">Info Pemilik</div>',                    
                    '<tpl if="status_info_kendaraan === 0">',
                        '<div class="text-center">', 
                            '<b><i><div style="margin: 0 0 10px 0;">Data belum tersedia!</div></i></b>',
                        '</div>', 
                    '<tpl elseif="status_info_kendaraan === 1">',
                        '<div class="row">', 
                            '<table class="table">',
                                '<tbody>',
                                    '<tr><th width="35%">Nama Pemilik</th><td width="65%">{nama_pemilik}</td></tr>',
                                    '<tr><th width="35%">Alamat</th><td width="65%">{alamat} {kota_kabupaten}</td></tr>',
                                '</tbody>',
                            '</table>',
                        '</div>', 
                    '<tpl elseif="status_info_kendaraan === 2">',
                        '<div class="text-center">', 
                            '<b><i><div style="color: #ff4500; margin: 0 0 10px 0;">Data tidak tersedia!</div></i></b>',
                        '</div>', 
                    '</tpl>',

                    '<div style="background-color: #8C8C8C; color: white; padding: 10px; margin: 0 0 10px 0; font-size: 17px;">Info Kendaraan</div>',
                    '<tpl if="status_info_kendaraan === 0">',
                        '<div class="text-center">', 
                            '<b><i><div style="margin: 0 0 10px 0;">Data belum tersedia!</div></i></b>',
                        '</div>', 
                    '<tpl elseif="status_info_kendaraan === 1">',
                        '<div class="row">', 
                            '<table class="table">',
                                '<tbody>',
                                    '<tr><th width="35%">Merk / Tahun</th><td width="65%">{kd_merek_kb} / {tahun_pembuatan}</td></tr>',
                                    '<tr><th width="35%">Model / Type</th><td width="65%">{kd_jenis_kb} / {type}</td></tr>',
                                    '<tr><th width="35%">Warna KB</th><td width="65%">{warna_kb}</td></tr>',
                                    '<tr><th width="35%">No. BPKB</th><td width="65%">{nomor_bpkb}</td></tr>',
                                    '<tr><th width="35%">No. Rangka</th><td width="65%">{no_rangka}</td></tr>',
                                    '<tr><th width="35%">No. Mesin</th><td width="65%">{no_mesin}</td></tr>',
                                    '<tr><th width="35%">Warna TNKB</th><td width="65%">{warna_plat}</td></tr>',
                                    '<tr><th width="35%">Habis Pajak</th><td width="65%">{tanggal_akhir_pajak}</td></tr>',
                                    '<tr><th width="35%">Habis STNK</th><td width="65%">{tanggal_akhir_stnk}</td></tr>',
                                    '<tr><th width="35%">Milik Ke</th><td width="65%">{milik_ke}</td></tr>',
                                '</tbody>',
                            '</table>',
                        '</div>', 
                    '<tpl elseif="status_info_kendaraan === 2">',
                        '<div class="text-center">', 
                            '<b><i><div style="color: #ff4500; margin: 0 0 10px 0;">Data tidak tersedia!</div></i></b>',
                        '</div>', 
                    '</tpl>',
                    
                    '<div style="background-color: #8C8C8C; color: white; padding: 10px; margin: 0 0 10px 0; font-size: 17px;">Info Administrasi Kendaraan</div>',
                    '<tpl if="status_info_kendaraan === 0">',
                        '<div class="text-center">', 
                            '<b><i><div style="margin: 0 0 10px 0;">Data belum tersedia!</div></i></b>',
                        '</div>', 
                    '<tpl elseif="status_info_kendaraan === 1">',
                        '<div class="row">', 
                            '<table class="table">',
                                '<tbody>',
                                    '<tr><th width="35%">Blokir KTP</th><td width="65%">{blokir_ktp}</td></tr>',
                                    '<tr><th width="35%">Status STNK</th><td width="65%">{status_stnk}</td></tr>',
                                    '<tr><th width="35%">Sts. Rubentina</th><td width="65%">{status_rubentina}</td></tr>',
                                '</tbody>',
                            '</table>',
                        '</div>', 
                    '<tpl elseif="status_info_kendaraan === 2">',
                        '<div class="text-center">', 
                            '<b><i><div style="color: #ff4500; margin: 0 0 10px 0;">Data tidak tersedia!</div></i></b>',
                        '</div>', 
                    '</tpl>', 

                    '<div style="background-color: #8C8C8C; color: white; padding: 10px; margin: 0 0 10px 0; font-size: 17px;">Info Pajak Kendaraan</div>',
                    /*'<div class="row">', 
                        '<table class="table">',
                            '<tbody>',
                                '<tr>',
                                    '<th width="25%" style="background-color: #ff4500; color: #fffafa;">&nbsp;</th>',
                                    '<th width="25%" style="background-color: #ff4500; color: #fffafa; text-align: right;">Pokok</th>',
                                    '<th width="25%" style="background-color: #ff4500; color: #fffafa; text-align: right;">Sanksi Adm</th>',
                                    '<th width="25%" style="background-color: #ff4500; color: #fffafa; text-align: right;">Jumlah</th>',
                                '</tr>',
                                '<tr>',
                                    '<th style="background-color: #ff4500; color: #fffafa;">BBNKP</th>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bbnkb_pokok)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bbnkb_sanksi_administratif)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bbnkb_jumlah)]}</td>',
                                '</tr>',
                                '<tr>',
                                    '<th style="background-color: #ff4500; color: #fffafa;">PKB</th>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.pkb_pokok)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.pkb_sanksi_administratif)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.pkb_jumlah)]}</td>',
                                '</tr>',
                                '<tr>',
                                    '<th style="background-color: #ff4500; color: #fffafa;">SWDKLLJ</th>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.sdwkllj_pokok)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.sdwkllj_sanksi_administratif)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.sdwkllj_jumlah)]}</td>',
                                '</tr>',
                                '<tr>',
                                    '<th style="background-color: #ff4500; color: #fffafa;">BEA STNK</th>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bea_stnk_pokok)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bea_stnk_sanksi_administratif)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bea_stnk_jumlah)]}</td>',
                                '</tr>',
                                '<tr>',
                                    '<th style="background-color: #ff4500; color: #fffafa;">BEA TNKB</th>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bea_tnkb_pokok)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bea_tnkb_sanksi_administratif)]}</td>',
                                    '<td style="text-align: right;">{[this.setFormatDecimal(values.bea_tnkb_jumlah)]}</td>',
                                '</tr>',
                                '<tr>',
                                    '<th style="background-color: #ff4500; color: #fffafa;">JUMLAH</th>',
                                    '<th style="background-color: #ff4500; color: #fffafa; text-align: right;">{[this.setFormatDecimal(values.jumlah_pokok)]}</th>',
                                    '<th style="background-color: #ff4500; color: #fffafa; text-align: right;">{[this.setFormatDecimal(values.jumlah_sanksi_administratif)]}</th>',
                                    '<th style="background-color: #ff4500; color: #fffafa; text-align: right;">{[this.setFormatDecimal(values.jumlah_total)]}</th>',
                                '</tr>',
                            '</tbody>',
                        '</table>',
                    '</div>',*/
                    '<tpl if="status_info_kendaraan === 0">',
                        '<div class="text-center">', 
                            '<b><i><div style="margin: 0 0 10px 0;">Data belum tersedia!</div></i></b>',
                        '</div>', 
                    '<tpl elseif="status_info_kendaraan === 1">',
                        '<div class="row">', 
                            '<table class="table">',
                                '<tbody>',
                                    '<tr><th width="100%" colspan="2" style="background-color: #ff4500; color: #fffafa;">POKOK</th></tr>',
                                    '<tr><th width="50%" style="background-color: #ff4500; color: #fffafa;">BBNKP</th><td width="50%" style="text-align: right;">{[this.setFormatDecimal(values.bbnkb_pokok)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">PKB</th><td style="text-align: right;">{[this.setFormatDecimal(values.pkb_pokok)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">SWDKLLJ</th><td style="text-align: right;">{[this.setFormatDecimal(values.sdwkllj_pokok)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">BEA STNK</th><td style="text-align: right;">{[this.setFormatDecimal(values.bea_stnk_pokok)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">BEA TNKB</th><td style="text-align: right;">{[this.setFormatDecimal(values.bea_tnkb_pokok)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">JUMLAH</th><th style="background-color: #ff4500; color: #fffafa; text-align: right;">{[this.setFormatDecimal(values.jumlah_pokok)]}</th></tr>',
                                '</tbody>',
                            '</table>',
                        '</div>',
                        
                        '<div class="row">', 
                            '<table class="table">',
                                '<tbody>',
                                    '<tr><th width="100%" colspan="2" style="background-color: #ff4500; color: #fffafa;">SANKSI ADMINISTRATIF</th></tr>',
                                    '<tr><th width="50%" style="background-color: #ff4500; color: #fffafa;">BBNKP</th><td width="50%" style="text-align: right;">{[this.setFormatDecimal(values.bbnkb_sanksi_administratif)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">PKB</th><td style="text-align: right;">{[this.setFormatDecimal(values.pkb_sanksi_administratif)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">SWDKLLJ</th><td style="text-align: right;">{[this.setFormatDecimal(values.sdwkllj_sanksi_administratif)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">BEA STNK</th><td style="text-align: right;">{[this.setFormatDecimal(values.bea_stnk_sanksi_administratif)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">BEA TNKB</th><td style="text-align: right;">{[this.setFormatDecimal(values.bea_tnkb_sanksi_administratif)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">JUMLAH</th><th style="background-color: #ff4500; color: #fffafa; text-align: right;">{[this.setFormatDecimal(values.jumlah_sanksi_administratif)]}</th></tr>',
                                '</tbody>',
                            '</table>',
                        '</div>',
                        
                        '<div class="row">', 
                            '<table class="table">',
                                '<tbody>',
                                    '<tr><th width="100%" colspan="2" style="background-color: #ff4500; color: #fffafa;">TOTAL PAJAK</th></tr>',
                                    '<tr><th width="50%" style="background-color: #ff4500; color: #fffafa;">BBNKP</th><td width="50%" style="text-align: right;">{[this.setFormatDecimal(values.bbnkb_jumlah)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">PKB</th><td style="text-align: right;">{[this.setFormatDecimal(values.pkb_jumlah)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">SWDKLLJ</th><td style="text-align: right;">{[this.setFormatDecimal(values.sdwkllj_jumlah)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">BEA STNK</th><td style="text-align: right;">{[this.setFormatDecimal(values.bea_stnk_jumlah)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">BEA TNKB</th><td style="text-align: right;">{[this.setFormatDecimal(values.bea_tnkb_jumlah)]}</td></tr>',
                                    '<tr><th style="background-color: #ff4500; color: #fffafa;">JUMLAH</th><th style="background-color: #ff4500; color: #fffafa; text-align: right;">{[this.setFormatDecimal(values.jumlah_total)]}</th></tr>',
                                '</tbody>',
                            '</table>',
                        '</div>', 
                    '<tpl elseif="status_info_kendaraan === 2">',
                        '<div class="text-center">', 
                            '<b><i><div style="color: #ff4500; margin: 0 0 10px 0;">Data tidak tersedia!</div></i></b>',
                        '</div>', 
                    '</tpl>', 

                    '<div style="background-color: #8C8C8C; color: white; padding: 10px; margin: 0 0 10px 0; font-size: 17px;">Info ETLE</div>',
                    '<tpl if="status_info_etle === 0">',
                        '<div class="text-center">', 
                            '<b><i><div style="margin: 0 0 10px 0;">Data belum tersedia!</div></i></b>',
                        '</div>', 
                    '<tpl elseif="status_info_etle === 1">',
                        '<div class="text-center">', 
                            '<b><i>Fitur ini masih Dalam Perbaikan!</i></b>',
                        '</div>', 
                    '<tpl elseif="status_info_etle === 2">',
                        '<div class="text-center">', 
                            '<b><i><div style="color: #ff4500; margin: 0 0 10px 0;">Data tidak tersedia!</div></i></b>',
                        '</div>', 
                    '</tpl>', 

                    '<div class="text-center">', 
                        '<button name="back">Tutup</button>', 
                    '</div>',

                '</div>',
                {
                    setFormatDecimal: function (value) {
                        var func = Ext.create('Admin.view.currency');
                        return (value>0?func.currency(value):'0');
                    }
                }
            ),

            listeners: {
                childtap: 'onSelect'
            } 
    }]
});
